apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: web 
  annotations:
    test: "to jest moja testowa aplikacja w podzie" 
spec:
  containers:
  - name: web
    image: nginx:1.14.2

