apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: delay
    image: busybox
    command: ['sh','-c','sleep 15']
  - name: download
    image: alpine
    command: ['sh','-c','apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/lxk-Sep.git /app; echo "Git repo cloned and inxdex.html saved"']
    volumeMounts:
    - name: app-data
      mountPath: /app
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: app-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: app-data
    emptyDir: {}

