apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-web-server
  name: test-web-server
spec:
  containers:
  - image: nginx
    name: test-web-server
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
