apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: web
    image: nginx
  - name: busybox
    image: busybox
    command: ['sh','-c','echo "ubuntu contianer started with success"; sleep 4h']

