apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: web
    env:
      - name: BRANCH_NAME
        valueFrom:
          configMapKeyRef:
            name: env-file-cm
            key: branchName
    envFrom:
      - configMapRef:
          name: my-configmap

