apiVersion: v1
kind: Pod
metadata:
  name: master-pod
spec:
  containers:
  - image: nginx
    name: c1
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
